todo_project/tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'

urlpatterns = [
   path('', views.task_list, name='list'),
   path('create/', views.create_task, name="create_task"),
   path('tasks/<int:task_id>/complete/', views.complete_task, name="complete_task"),
   path('tasks/<int:task_id>/remove/', views.remove_task, name="remove_task")
]

todo_project/todo_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),
]

todo_project/tasks/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
   title = models.CharField(max_length=200)
   description = models.TextField(blank=True)
   completed = models.BooleanField(default=False)
   created_at = models.DateTimeField(auto_now_add=True)

   def __str__(self):
      return self.title

todo_project/tasks/forms.py
from django import forms
from . import models

class TaskForm(forms.ModelForm):
   class Meta:
      model = models.Task
      fields = ['title', 'description', 'completed']

todo_project/tasks/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Task
from .forms import TaskForm

# Create your views here.

def task_list(request):
   tasks = Task.objects.all()
   return render(request, 'tasks/task_list.html', {'tasks': tasks})


def create_task(request):
   if request.method == 'POST':
      form = TaskForm(request.POST)
      if form.is_valid():
         form.save()
         return redirect('tasks:list')
   else:
      form = TaskForm()
   return render(request, 'tasks/task_form.html', {'form': form})

def complete_task(request, task_id):
   task = get_object_or_404(Task, id=task_id) #Busca objeto (Task) cujo id seja igual o id ou retorna um 404 caso não encontre
   if request.method == 'POST':
      task.completed = not task.completed
      task.save()
      return redirect('tasks:list')
   else:
      return redirect('tasks:create_task')
   
def remove_task(request, task_id):
   task = get_object_or_404(Task, id=task_id)
   if request.method == 'POST':
      task.delete()
      return redirect('tasks:list')
   else:
      return redirect('tasks:create_task')

todo_project/tasks/templates/tasks/task_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Task Detail</title>
</head>
<body>
   
</body>
</html>

todo_project/tasks/templates/tasks/task_form.html
{% extends "layout.html" %}

{% block title %}
   Create Task
{% endblock %}

{% block content %}
<form method="POST" class="create-task">
   {% csrf_token %}
   {% comment %} <input type="text" name="task" placeholder="Enter task"> {% endcomment %}
   {{ form.as_p }}
   <button type="submit">Add Task</button>
</form>
{% endblock %}

todo_project/tasks/templates/tasks/task_list.html
{% extends "layout.html" %}

   {% block title %}
      Task List  
   {% endblock %}
   
   {% block content %}
   <h1>Task List</h1>
   <ul>
      {% for task in tasks %}
         <li class="task">
            <h3>{{ task.title }}</h3>
            <form action="{% url 'tasks:remove_task' task.id %}" method="post" class="remove-task">
               {% csrf_token %}
               <input type="hidden" name="task-id" value="{{ task.id }}">
               <button type="submit">Remover tarefa</button>
            </form>
            <form action="{% url 'tasks:complete_task' task.id %}" method="post">
               {% csrf_token %}
               <input type="hidden" name="task-id" value="{{ task.id }}">
               <button type="submit">Marcar como concluido</button>
            </form>
            <p class="description" >Descrição: {{ task.description }}</p>
               <span>{% if task.completed %} Concluido {% else %} Não Concluido {% endif %}</span>
               <p class="date">Criado em: {{ task.created_at }}</p>
         </li>
      {% empty %}
         <li>No tasks found.</li>
      {% endfor %}
   </ul>

   <a href="{% url 'tasks:create_task' %}">Criar tarefa</a>
   {% endblock %}

todo_project/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>
      {% block title %}
      {% endblock %}
   </title>
   <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>
<body>
   {% block content %}
   {% endblock %}
</body>
</html>